spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

server:
  port: 0